spring:
  datasource:
    dynamic:
      datasource:
        master:
          username: sa
          password: ""
          url: jdbc:h2:mem:test
          driver-class-name: org.h2.Driver
        slave_1:
          username: sa
          password: ""
          url: jdbc:h2:mem:test1
          driver-class-name: org.h2.Driver
        slave_2:
          username: sa
          password: ""
          url: jdbc:h2:mem:test2
          driver-class-name: org.h2.Driver
        slave_3:
          username: sa
          password: ""
          url: jdbc:h2:mem:test3
          driver-class-name: org.h2.Driver

logging:
  level:
    com.baomidou: debug
swagger:
  base-package: com.baomidou.samples.ds.controller