spring:
  datasource:
    dynamic:
      druid: #以下是全局默认值，可以全局更改
        initial-size: 0
        max-active: 8
        min-idle: 2
        max-wait: -1
        min-evictable-idle-time-millis: 30000
        max-evictable-idle-time-millis: 30000
        time-between-eviction-runs-millis: 0
        validation-query: select 1
        validation-query-timeout: -1
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        pool-prepared-statements: true
        max-open-prepared-statements: 100
        filters: stat,wall
        share-prepared-statements: true
      datasource:
        master:
          username: root
          password: 123456
          url: jdbc:mysql://47.100.20.186:3306/dynamic?useSSL=false
          driver-class-name: com.mysql.jdbc.Driver
          druid: #这里可以重写默认值
            initial-size: 5
        slave_1:
          username: root
          password: 123456
          url: jdbc:mysql://47.100.20.186:3307/dynamic?useSSL=false
          driver-class-name: com.mysql.jdbc.Driver
          druid:
            initial-size: 6
        slave_2:
          username: root
          password: 123456
          url: jdbc:mysql://47.100.20.186:3308/dynamic?useSSL=false
          driver-class-name: com.mysql.jdbc.Driver
        slave_3:
          username: root
          password: 123456
          url: jdbc:mysql://47.100.20.186:3308/dynamic?useSSL=false
          driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com.baomidou: debug